[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
async-trait = "0.1.80"
dirs = "5.0.1"
futures = "0.3.30"
miette = "7.2.0"
once_cell = "1.19.0"
regex = { version = "1.10.4", default-features = false }
relative-path = "1.9.3"
reqwest = { version = "0.12.4", default-features = false }
rustc-hash = "1.1.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serde_yaml = "0.9.34"
thiserror = "1.0.61"
tokio = { version = "1.37.0", default-features = false, features = [
	"io-util",
	"rt",
	"sync",
] }
tracing = { version = "0.1.40" }
