[workspace]
resolver = "2"
members = ["crates/*", "examples/*"]

[workspace.dependencies]
async-trait = "0.1.83"
crossterm = "0.28.1"
dirs = "5.0.1"
iocraft = "0.5.0"
miette = "7.4.0"
regex = { version = "1.11.1", default-features = false }
relative-path = "1.9.3"
reqwest = { version = "0.12.9", default-features = false }
rustc-hash = "2.1.0"
serial_test = "3.2.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
serde_yaml = "0.9.34"
thiserror = "2.0.4"
tokio = { version = "1.42.0", default-features = false, features = [
    "io-util",
    "rt",
    "sync",
] }
tracing = { version = "0.1.41" }
