[package]
name = "starbase_sandbox"
version = "0.1.10"
edition = "2021"
license = "MIT"
description = "A temporary sandbox for testing file system and process operations, with fixtures support."
repository = "https://github.com/moonrepo/starbase"

[dependencies]
starbase_utils = { version = "0.3.1", path = "../utils", default-features = false }
assert_cmd = "2.0.12"
assert_fs = "1.0.13"
clean-path = "0.2.1"
insta = "1.31.0"
once_cell = { workspace = true }
predicates = "3.0.3"
pretty_assertions = "1.4.0"
