[package]
name = "starbase_macros"
version = "0.1.10"
edition = "2021"
license = "MIT"
description = "Macros for the starbase framework."
repository = "https://github.com/moonrepo/starbase"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.3"
proc-macro2 = "1.0.66"
quote = "1.0.31"
syn = { version = "2.0.18", features = ["full"] }

[features]
tracing = []
