[package]
name = "starbase_macros"
version = "0.8.7"
edition = "2024"
license = "MIT"
description = "Macros for the starbase framework."
repository = "https://github.com/moonrepo/starbase"
rust-version = "1.85.0"

[lib]
proc-macro = true

[dependencies]
darling = "0.21.3"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0.111", features = ["full"] }

[features]
events = []
tracing = []
